package dev.pratham.banking_ledger.reconciliation.domain.model;

public enum ReconciliationMismatchType {
    MATCHED,
    MISSING_INTERNAL_TRANSACTION,
    MISSING_EXTERNAL_SETTLEMENT,
    AMOUNT_MISMATCH,
    CURRENCY_MISMATCH,
    STATUS_MISMATCH,
    DUPLICATE_EXTERNAL_ITEM,
    DUPLICATE_INTERNAL_TRANSACTION,
    REVERSED_TRANSACTION_SETTLED,
    SETTLEMENT_DATE_OUT_OF_WINDOW
}
